// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;
using Firebase.Database;
using Foundation;

namespace ProyectoFinal
{
    public partial class GastoViewController : UIViewController
    {

        #region Variables

        DatabaseReference referenceBD;

        #endregion

        public GastoViewController(IntPtr handle) : base(handle)
        {
            //CerrarModal();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            referenceBD = Database.DefaultInstance.GetRootReference();

            Eventos();
        }

        void Eventos()
        {

            btnGuardarGasto.TouchUpInside += BtnGuardarGasto_TouchUpInside;;
        }

        public void NuevoGasto()
        {
            if (txtMonto.Text == "" || txtDescripcion.Text == "")
            {
                UIAlertView alert = new UIAlertView()
                {
                    Title = "Error!",
                    Message = "Ingresa datos por favor!"
                };
                alert.AddButton("OK");
                alert.Show();
            }
            else
            {

                var outcome = new Gasto
                {
                    Monto = int.Parse(txtMonto.Text),
                    Descripcion = txtDescripcion.Text,
                    Fecha = DateTime.Now
                };

                object[] keys = { "Monto", "Descripcion", "Fecha" };
                object[] values = { outcome.Monto, outcome.Descripcion, outcome.Fecha };

                DatabaseReference Gasto = referenceBD.GetChild("Gastos");
                var data = NSDictionary.FromObjectsAndKeys(values, keys, keys.Length);

                Gasto.SetValue(data);
                txtMonto.Text = "";
                txtDescripcion.Text = "";
                UIAlertView alert = new UIAlertView()
                {
                    Title = "Exito!",
                    Message = "Ingreso registrado exitosamente!"
                };
                alert.AddButton("OK");
                alert.Show();
            }
        }

       
        void BtnGuardarGasto_TouchUpInside(object sender, EventArgs e)
        {
            NuevoGasto();
        }

    }
}
