// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ProyectoFinal
{
	public partial class GastoViewController : UIViewController
	{
		public GastoViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
