// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Firebase.Database;
using Foundation;
using UIKit;

namespace ProyectoFinal
{
    public partial class GastosTableViewController : UITableViewController, IUITableViewDataSource, IUITableViewDelegate
    {
        public GastosTableViewController(IntPtr handle) : base(handle)
        {
        }

        #region Variables

        DatabaseReference referenceBD;
        List<Gasto> lstgasto;

        #endregion

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            referenceBD = Database.DefaultInstance.GetRootReference();
            lstgasto = new List<Gasto>();
            Consultargastos();
            OutcomeTable.DataSource = this;
            OutcomeTable.ReloadData();
        }

        void Consultargastos()
        {
            lstgasto.Clear();

            DatabaseReference outcomes = referenceBD.GetChild("Gastos");

            nuint handleReference = outcomes.ObserveEvent(DataEventType.Value, (snapshot) =>
            {
                var data = snapshot.GetValue<NSDictionary>();

                var gasto = new Gasto
                {
                    Monto = float.Parse(data["Monto"].ToString()),
                    Descripcion = data["Descripcion"].ToString(),
                    Fecha = DateTime.Parse(data["Fecha"].ToString())
                };

                lstgasto.Add(gasto);
                OutcomeTable.ReloadData();

            });
        }

        #region TableView Datasource

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("GastoTableViewCell", indexPath);
            cell.TextLabel.Text = lstgasto[indexPath.Row].ToString();
            return cell;
        }

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return lstgasto.Count;
        }

        [Export("numberOfSectionsInTableView:")]
        public override nint NumberOfSections(UITableView tableView)
        {
            return 1;
        }

        #endregion


    }
}
