// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ProyectoFinal
{
	public partial class IngresoViewController : UIViewController
	{
		public IngresoViewController (IntPtr handle) : base (handle)
		{
            CerrarModal();
		}

        void CerrarModal(){
            btnCancelar.TouchUpInside += (sender, e) => {
                ViewController v = new ViewController();
                v.DismissViewController(true,null);
            };
        }

        void NuevoIngreso() {
            DatabaseReference rootNode = Database.DefaultInstance.GetRootReference();
        }
	}
}
