// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ProyectoFinal
{
	public partial class IngresosTableViewController : UITableViewController
	{
		public IngresosTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
