// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;
using Firebase.Database;
using Firebase;
using Foundation;

namespace ProyectoFinal
{
    public partial class IngresoViewController : UIViewController
    {
        void BtnGuardarIngreso_TouchUpInside(object sender, EventArgs e)
        {
        }


        #region Variables

        DatabaseReference referenceBD;

        #endregion

        public IngresoViewController (IntPtr handle) : base (handle)
        {
            //CerrarModal();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            referenceBD = Database.DefaultInstance.GetRootReference();
            //Eventos();
        }

        public void NuevoIngreso() {

            if (txtMonto.Text == "" || txtDescripcion.Text == "")
            {
                UIAlertView alert = new UIAlertView()
                {
                    Title = "Error!",
                    Message = "Ingrese datos por favor!"
                };
                alert.AddButton("OK");
                alert.Show();
            }
            else
            {

                var income = new Ingreso
                {
                    Monto = int.Parse(txtMonto.Text),
                    Descripcion = txtDescripcion.Text,
                    Fecha = DateTime.Now
                };

                object[] keys = { "Monto", "Descripcion", "Fecha" };
                object[] values = { income.Monto, income.Descripcion, income.Fecha.ToString() };


                DatabaseReference Ingreso = referenceBD.GetChild("Ingresos");
                var data = NSDictionary.FromObjectsAndKeys(values, keys, keys.Length);

                Ingreso.SetValue(data);
                txtMonto.Text = "";
                txtDescripcion.Text = "";
                UIAlertView alert = new UIAlertView()
                {
                    Title = "Exito!",
                    Message = "Ingreso registrado exitosamente!"
                };
                alert.AddButton("OK");
                alert.Show();
            }
        }
        partial void btnGuardar(NSObject sender)
        {
            NuevoIngreso();
        }
    }
}
