// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Firebase.Database;
using Foundation;
using UIKit;

namespace ProyectoFinal
{
    public partial class IngresosTableViewController : UITableViewController, IUITableViewDataSource, IUITableViewDelegate
	{
		public IngresosTableViewController (IntPtr handle) : base (handle)
		{
		}

        #region Variables

        DatabaseReference referenceBD;
        List<Ingreso> lstIngreso;

        #endregion

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            referenceBD = Database.DefaultInstance.GetRootReference();
            lstIngreso = new List<Ingreso>();
            ConsultarIngresos();
            IncomeTable.DataSource = this;
            IncomeTable.ReloadData();
        }

        void ConsultarIngresos() {
            lstIngreso.Clear();

            DatabaseReference incomes = referenceBD.GetChild("Ingresos");

            nuint handleReference = incomes.ObserveEvent(DataEventType.Value, (snapshot) =>
            {
                var data = snapshot.GetValue<NSDictionary>();

                var ingreso = new Ingreso
                {
                    Monto = float.Parse(data["Monto"].ToString()),
                    Descripcion = data["Descripcion"].ToString(),
                    Fecha = DateTime.Parse(data["Fecha"].ToString())
                };

                lstIngreso.Add(ingreso);
                IncomeTable.ReloadData();

            });
        }

        #region TableView Datasource

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("IngresoTableViewCell", indexPath);
            cell.TextLabel.Text = lstIngreso[indexPath.Row].ToString();
            return cell;
        }

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return lstIngreso.Count;
        }

        [Export("numberOfSectionsInTableView:")]
        public override nint NumberOfSections(UITableView tableView)
        {
            return 1;
        }

        #endregion


    }
}
